services:
  mysql:
    image: mysql:8.4
    container_name: zivro-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zivro
    ports:
      - "3306:3306"
    volumes:
      - zivro_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  zivro_mysql_data:
